[package]
name = "blink"
version = "0.1.0"
authors = ["Marvin Ouma <pancakesdeath@protonmail.com>"]
edition = "2018"

[dependencies]
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
panic-semihosting = "0.5.3"

[dependencies.stm32f1xx-hal]
version = "0.6.1"
features = ["stm32f103", "rt"]
